config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'rides#index'
  devise_for :accounts
  scope module: 'api/v1', path: 'api/v1' do
    resources :rides, only: [:index]
  end
  resources :rides, only: [:index, :show, :create]
end

app/models/account.rb
class Account < ApplicationRecord
  include AddressValidatorConcern

  devise    :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

  has_many  :rides
  validates :home_address, presence: true

  enum role: {rider: 0, driver: 1}
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/address_validator_concern.rb
# frozen_string_literal: true

module AddressValidatorConcern
  extend ActiveSupport::Concern

  included do
    validate :validate_address_attributes
  end

  private

  def validate_address_attributes
    attributes.each do |attribute, value|
      if address_attribute?(attribute) && !valid_address?(value)
        errors.add(attribute, 'Address only allowed in format [longitude, latitude]')
      end
    end
  end

  def address_attribute?(attribute)
    attribute.to_s.include?('address')
  end

  def valid_address?(value)
    value.is_a?(Array) && value.size == 2 && value.all? { |v| num?(v) }
  end

  def num?(value)
    Float(value)
    true
  rescue StandardError
    false
  end
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  include AddressValidatorConcern

  belongs_to :account
  enum status: {open: 0, close: 1, in_progress: 2}

  validates :start_address, :destination_address, presence: true

end

app/controllers/api/v1/rides_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class RidesController < ApplicationController
      include Api::V1::RidesHelper
      include RidesCacheConcern
      before_action :fetch_driver, only: [:index]
      rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
      def index
        @rides = Ride.open
        @computed_rides = []
        @rides.each { |ride| @computed_rides.push cached_computed_ride ride }
        @computed_rides.sort! { |a, b| b['score'] <=> a['score'] }
        @rides = paginated_rides
        respond_to do |format|
          format.json {render json:@rides}
          format.html {render 'api/v1/rides/index' }
        end
      end

      private

      def paginated_rides
        @computed_rides.paginate(page: params[:page] || 1,
                                 per_page: params[:per_page] || 4)
      end

      def record_not_found
        render json: {
          error: 'Driver not found'
        }, status: :not_found
      end

      def fetch_driver
        @driver = Account.find(params[:driver].to_s)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
require 'json'
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    params[:account][:home_address] = JSON.parse(params[:account][:home_address]) if
      params.dig(:account, :home_address).present?

    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, { home_address: [] }])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role, { home_address: [] }])
  end
end

app/controllers/concerns/rides_cache_concern.rb
# frozen_string_literal: true

module RidesCacheConcern
  extend ActiveSupport::Concern

  included do
    def cached_computed_ride(ride)
      cache_key = [@driver.home_address, ride.start_address, ride.destination_address]
      cache = CacheService.new
      if cache.cache_exists? cache_key
        return JSON.parse(cache.fetch_cache(cache_key).gsub('=>', ':').gsub(/\bnil\b/, 'null'))
      end
      value = ride_calculator(
        ride, OpenRouteService.new.fetch_direction(@driver.home_address, ride.start_address,
                                                   ride.destination_address).body
      )
      cache.set_cache cache_key, value
      value
    end
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_ride, only: [:show]

  def index
    @rides = Ride.all
  end

  def show
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.new(ride_params)

    if @ride.save
      redirect_to @ride, notice: t(:created)
    else
      render :new
    end
  end

  private
    def set_ride
      @ride = Ride.find(params[:id])
    end

    def ride_params
      params.require(:ride).permit(:start_address, :destination_address)
    end
end

app/helpers/api/v1/rides_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module RidesHelper
      def ride_calculator(ride, distance_service_object)
        distance_service_object = JSON.parse(distance_service_object)
        routes = distance_service_object['routes']
        computed_service_object = compute_routes_object routes
        computed_service_object[:ride_id] = ride.id
        computed_service_object[:ride_start_destination_address] = [ride.start_address, ride.destination_address]
        computed_service_object
      end

      def compute_routes_object(routes)
        rec = ActiveSupport::HashWithIndifferentAccess.new
        rec[:driving_distance] = routes.first['summary']['distance']
        rec[:driving_duration] = seconds_to_hours routes.first['summary']['duration']
        rec[:commute_distance] = routes.first['segments'].first['distance']
        rec[:commute_duration] = seconds_to_hours routes.first['segments'].first['duration']
        rec[:ride_distance] = routes.first['segments'][1]['distance']
        rec[:ride_duration] = seconds_to_hours routes.first['segments'][1]['duration']
        rec[:ride_earnings] = calculate_ride_earning rec[:ride_distance],
                                                     rec[:ride_duration]
        rec[:score] = calculate_score rec[:ride_earnings],
                                      rec[:commute_duration],
                                      rec[:ride_duration]
        rec
      end

      def calculate_ride_earning(distance, time)
        12 + 1.5 * (distance > 5 ? distance - 5 : 0) +
          0.7 * (hours_to_minutes(time) > 15 ? hours_to_minutes(time) - 15 : 0)
      end

      def calculate_score(earnings, commute, ride)
        earnings / (commute + ride)
      end

      def seconds_to_hours(time)
        Float(time) / 3600
      rescue StandardError => e
        0
      end

      def hours_to_minutes(time)
        Float(time) * 60
      rescue StandardError => e
        0
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<header class="p-3  text-white ">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img src="https://static.vecteezy.com/system/resources/previews/007/586/808/original/map-pointer-with-bicycle-rider-icon-illustration-vector.jpg"
                    style="width: 90px" alt="logo">
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to 'Home', root_path,class: "nav-link px-2 text-white" %> </li>
      </ul>
      <div class="text-end d-flex">
          <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-info me-3" %>
          <%= button_to "Sign out", destroy_account_session_path, class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartRouting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
    <div class="container">
      <%if alert.present?%>
   <div class="alert alert-danger"> <%= alert %></div>
   <%elsif notice.present?%>
   <div class="alert alert-success"> <%= notice %></div>
   <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rides/_form.html.erb
<!-- views/rides/_form.html.erb -->
<div class="container">
<%= form_for @ride do |f| %>
  <div class="form-group">
    <%= f.label :start_address %>
    <%= f.select :start_address, [['McPherson County', [-101.244478, 41.487089].to_json],
        ['Velly County', [-98.893404, 41.404738].to_json],['McPherson park', [-101.244478, 41.487089].to_json], ['County Park', [-101.244478, 41.487089].to_json]]%>
  </div>

  <div class="form-group">
    <%= f.label :destination_address %>
    <%= f.select :destination_address, [['McPherson County', [-101.244478, 41.487089].to_json],
        ['Velly County', [-98.893404, 41.404738].to_json],['McPherson park', [-101.244478, 41.487089].to_json], ['County Park', [-101.244478, 41.487089].to_json]]%>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/rides/_ride.html.erb
<tr>
  <td><%= ride.status %></td>
  <td><%= ride.start_address %></td>
  <td><%= ride.destination_address %></td>
  <td >
    <%= link_to "Show", ride_path(ride), class: "btn btn-info"%>
  </td>
</tr>

app/views/rides/index.html.erb
<h1>Rides</h1>

<%if @rides.length > 0%>
  <table class="table table-striped">
    <tr>
      <th scope= "col">Status</th>
      <th scope= "col">Start Address</th>
      <th scope= "col">Destination Address</th>
      <th scope= "col">Actions</th>
    </tr>
    <%= render partial: "ride", collection: @rides %>
  </table>
<% else %>
  <div class="alert alert-info" role="alert">
    There are no open rides yet!
  </div>
<% end %>

<h1>You Can Find Nearest Rides</h1>
  <%= link_to "Find Rides", rides_path(driver: current_account.id), class: "btn btn-info" %>

app/views/rides/new.html.erb
<!-- views/rides/new.html.erb -->
<div class= "container">
<h1>New Ride</h1>

<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-secondary" %>
</div>

app/views/rides/show.html.erb
<!-- views/rides/show.html.erb -->

<h1>Ride Details</h1>

<p><strong>ID:</strong> <%= @ride.id %></p>
<p><strong>Status:</strong> <%= @ride.status %></p>
<p><strong>Start Address:</strong> <%= @ride.start_address %></p>
<p><strong>Destination Address:</strong> <%= @ride.destination_address %></p>

<%= link_to "Back", root_path, class: "btn btn-secondary" %>